Add config and data reading

diff --git a/confman b/confman
--- a/confman
+++ b/confman
@@ -1,9 +1,34 @@
 #!/bin/sh
 
+# Start of Public API
+
+# Adds a repository.
+#
+# Parameters:
+# - Name (only the ascii letters, hyphen, and underscore are allowed)
+# - Local path (newlines not allowed currently)
+# - Git url (will be cloned to the local path)
+add_repository() {
+    if [ $# != 0 ]; then
+        echo 'error: add_repository takes 2 or 3 arguments' >&2
+        return 1
+    fi
+
+    # TODO: Validate the arguments.
+
+    printf '%s %s %s\n' "$1" "$2" "$3"
+}
+
+# End of Public API
+# Anything beyond this point should not be relied upon in user configuration since it may change in a minor release.
+
 error() {
     printf 'error: %s\n' "$1" >&2
     exit 1
 }
+
+NEWLINE='
+'
 
 operation=
 
@@ -181,7 +206,67 @@ process_argument() {
     esac
 }
 
+# Newline separated list of space separated triples of repository name, path, and git url.
+repositories=
+# Newline separated list of package names.
+installed_packages=
+# Newline separated list of package names.
+explicitly_installed_packages=
+
+read_all_configuration() {
+    for configuration_directory in '/etc' "${XDG_CONFIG_HOME-"$HOME/.config"}"; do
+        read_configuration
+    done
+}
+
+unset configuration_directory
+unset repositories_file
+unset line
+read_configuration() {
+    repositories_file="$configuration_directory/confman/repositories"
+
+    if [ -e "$repositories_file" ]; then
+        # shellcheck disable=SC1090
+        (. "$repositories_file") |
+            while IFS= read -r entry; do
+                repositories="$repositories$NEWLINE$entry"
+            done
+    fi
+}
+
+read_all_data() {
+    xdg_data_dirs="${XDG_DATA_DIRS-/usr/local/share/:/usr/share/}"
+
+    for data_directory in \
+        "${xdg_data_dirs%%:*}" \
+        "${XDG_DATE_HOME-"$HOME/.local/share"}"; do
+        read_data
+    done
+}
+
+read_packages_file() {
+    if [ -e "$1" ]; then
+        # Filter out blank lines and comments.
+        sed '/^\s*#/d;/^\s*$/d' <"$1"
+    fi
+}
+
+unset data_directory
+unset installed_packages_file
+unset explicitly_installed_packages_file
+read_data() {
+    installed_packages_file="$data_directory/confman/installed packages"
+    explicitly_installed_packages_file="$data_directory/confman/explicitly installed packages"
+
+    installed_packages="$installed_packages$NEWLINE$(read_packages_file "$installed_packages_file")"
+
+    explicitly_installed_packages="$explicitly_installed_packages$NEWLINE$(read_packages_file "$explicitly_installed_packages_file")"
+}
+
 main() {
+    read_all_configuration
+    read_all_data
+
     for argument in "$@"; do
         process_argument
     done
